name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-rc1
      - name: Lint
        continue-on-error: true # TODO: Remove when 1.16 linting starts passing.
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
      - name: Test
        run: go test ./... -cover -race
